/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package usersForm.Bendahara;

import DataAccessObject.WargaDAO;
import model.Warga;
import java.util.List;
import java.sql.*;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
//import org.apache.poi.ss.usermodel.*;
//import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import database.Koneksi;

/**
 *
 * @author HYPE AMD
 */
public class panelDashboardBendahara extends javax.swing.JPanel {

    private int idLingkungan;
    
    /**
     * Creates new form panelDashboardBendahara
     */
    public panelDashboardBendahara() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblSaldoLingkungan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPendapatanHariIni = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblPengeluaranHariIni = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblJumlahWarga = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlExportData = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRiwayatTransaksi = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Dashboard");

        jLabel2.setText("Bendahara /");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Dashboard");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Lingkungan");

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Saldo");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Dollar Bag.png"))); // NOI18N

        lblSaldoLingkungan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldoLingkungan.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldoLingkungan.setText("Rp.1.000.000,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(104, 104, 104))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSaldoLingkungan)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(lblSaldoLingkungan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pendapatan hari ini");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Profit.png"))); // NOI18N

        lblPendapatanHariIni.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPendapatanHariIni.setForeground(new java.awt.Color(0, 255, 0));
        lblPendapatanHariIni.setText("+Rp.600.000,00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblPendapatanHariIni)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(lblPendapatanHariIni)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pengeluaran hari ini");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Financial Decline.png"))); // NOI18N

        lblPengeluaranHariIni.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPengeluaranHariIni.setForeground(new java.awt.Color(255, 0, 0));
        lblPengeluaranHariIni.setText("-Rp.120.000,00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPengeluaranHariIni)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(lblPengeluaranHariIni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah Warga");

        lblJumlahWarga.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJumlahWarga.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahWarga.setText("24");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(99, 99, 99))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblJumlahWarga)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(lblJumlahWarga)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(245, 245, 245));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Riwayat Transaksi");

        pnlExportData.setBackground(new java.awt.Color(245, 245, 245));
        pnlExportData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExportDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExportDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExportDataMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Export Data");

        javax.swing.GroupLayout pnlExportDataLayout = new javax.swing.GroupLayout(pnlExportData);
        pnlExportData.setLayout(pnlExportDataLayout);
        pnlExportDataLayout.setHorizontalGroup(
            pnlExportDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExportDataLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        pnlExportDataLayout.setVerticalGroup(
            pnlExportDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExportDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblRiwayatTransaksi.setBackground(new java.awt.Color(245, 245, 245));
        tblRiwayatTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRiwayatTransaksi);

        btnRefresh.setBackground(new java.awt.Color(0, 204, 204));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlExportData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefresh)))
                    .addComponent(pnlExportData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addGap(7))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlExportDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExportDataMouseClicked
        exportToCSV();
    }//GEN-LAST:event_pnlExportDataMouseClicked

    private void pnlExportDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExportDataMouseEntered
        if (pnlExportData.getBackground().equals(new java.awt.Color(245,245,245))) {
            pnlExportData.setBackground(new java.awt.Color(153,153,255));
        }
    }//GEN-LAST:event_pnlExportDataMouseEntered

    private void pnlExportDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExportDataMouseExited
        if (pnlExportData.getBackground().equals(new java.awt.Color(153,153,255))) {
            pnlExportData.setBackground(new java.awt.Color(245, 245, 245));
        }
    }//GEN-LAST:event_pnlExportDataMouseExited

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        setDataKeuangan(idLingkungan);
        loadRiwayatTransaksi(idLingkungan);
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * Set the environment ID for this panel
     * @param idLingkungan The environment ID
     */
    public void setLingkungan(int idLingkungan) {
        this.idLingkungan = idLingkungan;
        WargaDAO wargaDAO = new WargaDAO();
        int jumlah = 0;
        try {
            // Ambil semua warga pada lingkungan ini
            String sql = "SELECT COUNT(*) FROM warga WHERE id_lingkungan = ? AND status = 'aktif'";
            java.sql.Connection conn = database.Koneksi.getConnection();
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idLingkungan);
            java.sql.ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                jumlah = rs.getInt(1);
            }
            rs.close();
            ps.close();
        } catch (Exception e) {
            jumlah = 0;
        }
        lblJumlahWarga.setText(String.valueOf(jumlah));
        // Tambahan: muat riwayat transaksi
        loadRiwayatTransaksi(idLingkungan);
    }

    // Tambahan: method untuk mengisi data keuangan lingkungan
    public void setDataKeuangan(int idLingkungan) {
        try {
            java.sql.Connection conn = database.Koneksi.getConnection();
            // Saldo: total pemasukan - total pengeluaran
            String sqlSaldo = "SELECT " +
                "COALESCE((SELECT SUM(jumlah) FROM transaksi WHERE id_lingkungan=? AND tipe='pemasukan'),0) - " +
                "COALESCE((SELECT SUM(jumlah) FROM transaksi WHERE id_lingkungan=? AND tipe='pengeluaran'),0) AS saldo";
            java.sql.PreparedStatement psSaldo = conn.prepareStatement(sqlSaldo);
            psSaldo.setInt(1, idLingkungan);
            psSaldo.setInt(2, idLingkungan);
            java.sql.ResultSet rsSaldo = psSaldo.executeQuery();
            if (rsSaldo.next()) {
                int saldo = rsSaldo.getInt("saldo");
                lblSaldoLingkungan.setText("Rp." + String.format("%,d", saldo));
            }
            rsSaldo.close();
            psSaldo.close();

            // Pendapatan hari ini
            String sqlPendapatan = "SELECT COALESCE(SUM(jumlah),0) FROM transaksi WHERE id_lingkungan=? AND tipe='pemasukan' AND DATE(tanggal)=CURDATE()";
            java.sql.PreparedStatement psPendapatan = conn.prepareStatement(sqlPendapatan);
            psPendapatan.setInt(1, idLingkungan);
            java.sql.ResultSet rsPendapatan = psPendapatan.executeQuery();
            if (rsPendapatan.next()) {
                int pendapatan = rsPendapatan.getInt(1);
                lblPendapatanHariIni.setText("+Rp." + String.format("%,d", pendapatan));
            }
            rsPendapatan.close();
            psPendapatan.close();

            // Pengeluaran hari ini
            String sqlPengeluaran = "SELECT COALESCE(SUM(jumlah),0) FROM transaksi WHERE id_lingkungan=? AND tipe='pengeluaran' AND DATE(tanggal)=CURDATE()";
            java.sql.PreparedStatement psPengeluaran = conn.prepareStatement(sqlPengeluaran);
            psPengeluaran.setInt(1, idLingkungan);
            java.sql.ResultSet rsPengeluaran = psPengeluaran.executeQuery();
            if (rsPengeluaran.next()) {
                int pengeluaran = rsPengeluaran.getInt(1);
                lblPengeluaranHariIni.setText("-Rp." + String.format("%,d", pengeluaran));
            }
            rsPengeluaran.close();
            psPengeluaran.close();
        } catch (Exception e) {
            lblSaldoLingkungan.setText("Rp.0");
            lblPendapatanHariIni.setText("+Rp.0");
            lblPengeluaranHariIni.setText("-Rp.0");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJumlahWarga;
    private javax.swing.JLabel lblPendapatanHariIni;
    private javax.swing.JLabel lblPengeluaranHariIni;
    private javax.swing.JLabel lblSaldoLingkungan;
    private javax.swing.JPanel pnlExportData;
    private javax.swing.JTable tblRiwayatTransaksi;
    // End of variables declaration//GEN-END:variables

    public void loadRiwayatTransaksi(int idLingkungan) {
        try {
            java.sql.Connection conn = database.Koneksi.getConnection();
            String sql = "SELECT t.id, t.tipe, t.jenis, t.jumlah, t.tanggal, t.sumber, t.keterangan, " +
                         "COALESCE(v.status, CASE WHEN t.tipe='pemasukan' THEN 'disetujui' ELSE '-' END) AS status " +
                         "FROM transaksi t LEFT JOIN verifikasi_transaksi v ON t.id = v.id_transaksi " +
                         "WHERE t.id_lingkungan = ? ORDER BY t.tanggal DESC";
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idLingkungan);
            java.sql.ResultSet rs = ps.executeQuery();
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[]{"ID", "Tipe", "Jenis", "Jumlah", "Tanggal", "Sumber", "Keterangan", "Status"}, 0
            );
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("tipe"),
                    rs.getString("jenis"),
                    rs.getInt("jumlah"),
                    rs.getTimestamp("tanggal"),
                    rs.getString("sumber"),
                    rs.getString("keterangan"),
                    rs.getString("status")
                });
            }
            tblRiwayatTransaksi.setModel(model);
            // Set warna header tabel dengan custom renderer agar tidak diabaikan L&F
            javax.swing.table.JTableHeader header = tblRiwayatTransaksi.getTableHeader();
            header.setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
                @Override
                public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                    java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    c.setBackground(new java.awt.Color(0, 51, 102));
                    c.setForeground(java.awt.Color.WHITE);
                    setHorizontalAlignment(CENTER);
                    setFont(getFont().deriveFont(java.awt.Font.BOLD));
                    return c;
                }
            });
            // Set semua isi tabel rata tengah
            javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            for (int i = 0; i < tblRiwayatTransaksi.getColumnCount(); i++) {
                tblRiwayatTransaksi.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
            // Set custom renderer untuk kolom Tipe dan Jumlah (override center jika perlu)
            tblRiwayatTransaksi.getColumnModel().getColumn(1).setCellRenderer(new PengeluaranCellRenderer(1)); // Tipe
            tblRiwayatTransaksi.getColumnModel().getColumn(3).setCellRenderer(new CurrencyIDRCellRenderer()); // Jumlah
            rs.close();
            ps.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat riwayat transaksi: " + e.getMessage());
        }
    }

    // Custom renderer untuk kolom tipe dan jumlah
    private static class PengeluaranCellRenderer extends javax.swing.table.DefaultTableCellRenderer {
        private final int tipeColumnIndex;
        public PengeluaranCellRenderer(int tipeColumnIndex) {
            this.tipeColumnIndex = tipeColumnIndex;
        }
        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            String tipe = table.getValueAt(row, 1).toString(); // kolom 1 adalah tipe
            if ("pengeluaran".equalsIgnoreCase(tipe)) {
                c.setForeground(java.awt.Color.RED);
            } else if ("pemasukan".equalsIgnoreCase(tipe)) {
                c.setForeground(new java.awt.Color(0, 153, 0)); // hijau
            } else {
                c.setForeground(java.awt.Color.BLACK);
            }
            return c;
        }
    }

    // Renderer khusus untuk kolom jumlah agar tampil format IDR
    private static class CurrencyIDRCellRenderer extends javax.swing.table.DefaultTableCellRenderer {
        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            if (value instanceof Number) {
                java.text.NumberFormat format = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
                setText(format.format(((Number) value).intValue()));
            } else {
                setText(value != null ? value.toString() : "");
            }
            // Pewarnaan tetap mengikuti tipe transaksi
            String tipe = table.getValueAt(row, 1).toString();
            if ("pengeluaran".equalsIgnoreCase(tipe)) {
                c.setForeground(java.awt.Color.RED);
            } else if ("pemasukan".equalsIgnoreCase(tipe)) {
                c.setForeground(new java.awt.Color(0, 153, 0));
            } else {
                c.setForeground(java.awt.Color.BLACK);
            }
            return c;
        }
    }

    private void exportToCSV() {
        try {
            // Buat file chooser
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Simpan Data Transaksi (CSV)");
            fileChooser.setFileFilter(new FileNameExtensionFilter("CSV Files (*.csv)", "csv"));
            
            // Set nama file default
            SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd_HHmmss");
            String defaultFileName = "Data_Transaksi_" + sdf.format(new Date()) + ".csv";
            fileChooser.setSelectedFile(new File(defaultFileName));
            
            int result = fileChooser.showSaveDialog(this);
            if (result != JFileChooser.APPROVE_OPTION) {
                return;
            }
            
            File file = fileChooser.getSelectedFile();
            if (!file.getName().toLowerCase().endsWith(".csv")) {
                file = new File(file.getAbsolutePath() + ".csv");
            }
            
            // Tulis ke file CSV
            java.io.PrintWriter writer = new java.io.PrintWriter(file, "UTF-8");
            
            // Header
            writer.println("No,ID,Tipe,Jenis,Jumlah,Tanggal,Sumber,Keterangan");
            
            // Ambil data dari database
            Connection conn = Koneksi.getConnection();
            String sql = "SELECT id, tipe, jenis, jumlah, tanggal, sumber, keterangan FROM transaksi WHERE id_lingkungan = ? ORDER BY tanggal DESC";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idLingkungan);
            ResultSet rs = ps.executeQuery();
            
            int rowNum = 1;
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            
            while (rs.next()) {
                StringBuilder line = new StringBuilder();
                line.append(rowNum).append(",");
                line.append(rs.getInt("id")).append(",");
                line.append("\"").append(rs.getString("tipe")).append("\",");
                line.append("\"").append(rs.getString("jenis")).append("\",");
                line.append(rs.getInt("jumlah")).append(",");
                line.append("\"").append(dateFormat.format(rs.getTimestamp("tanggal"))).append("\",");
                line.append("\"").append(rs.getString("sumber")).append("\",");
                line.append("\"").append(rs.getString("keterangan")).append("\"");
                
                writer.println(line.toString());
                rowNum++;
            }
            
            rs.close();
            ps.close();
            writer.close();
            
            JOptionPane.showMessageDialog(this, 
                "Data berhasil diexport ke CSV:\n" + file.getAbsolutePath(), 
                "Export Berhasil", 
                JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error saat export data CSV: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
}
