/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package usersForm.Ketua;

import DataAccessObject.WargaDAO;
import DataAccessObject.NotifikasiDAO;
import model.Warga;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author HYPE AMD
 */
public class panelKomunikasi extends javax.swing.JPanel {

    /**
     * Creates new form panelKomunikasi
     */
    // Konstruktor panel, inisialisasi komponen dan event listener broadcast
    public panelKomunikasi() {
        initComponents();
        brWarga.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                handleBroadcast();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taPesanKetua = new javax.swing.JTextArea();
        brWarga = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Komunikasi");

        jLabel2.setText("Bendahara /");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Komunikasi");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Pesan");

        taPesanKetua.setColumns(20);
        taPesanKetua.setRows(5);
        jScrollPane1.setViewportView(taPesanKetua);

        brWarga.setBackground(new java.awt.Color(153, 255, 204));
        brWarga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        brWarga.setText("Broadcast Ke Warga");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(brWarga, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(brWarga, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 520, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Mendapatkan id_lingkungan dari parent frame (KetuaToolsPage)
    private Integer getIdLingkunganFromParent() {
        java.awt.Container parent = getParent();
        while (parent != null && !(parent instanceof KetuaToolsPage)) {
            parent = parent.getParent();
        }
        if (parent instanceof KetuaToolsPage) {
            KetuaToolsPage ktp = (KetuaToolsPage) parent;
            if (ktp.getLingkungan() != null) {
                return ktp.getLingkungan().getId();
            } else if (ktp.getPengguna() != null) {
                return ktp.getPengguna().getIdLingkungan();
            }
        }
        return null;
    }

    // Menangani aksi broadcast pesan ke warga
    private void handleBroadcast() {
        Integer idLingkungan = getIdLingkunganFromParent();
        if (idLingkungan == null) {
            JOptionPane.showMessageDialog(this, "Gagal mendapatkan lingkungan user.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String pesan = taPesanKetua.getText().trim();
        if (pesan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pesan tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String[] opsi = {"Seluruh Warga", "Warga Spesifik"};
        int pilihan = JOptionPane.showOptionDialog(this, "Pilih tujuan broadcast:", "Broadcast", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opsi, opsi[0]);
        if (pilihan == 0) {
            // Broadcast ke seluruh warga
            WargaDAO wargaDAO = new WargaDAO();
            List<Warga> wargaList = wargaDAO.getAllWargaByLingkungan(idLingkungan);
            int sukses = 0;
            for (Warga w : wargaList) {
                if (NotifikasiDAO.insertNotifikasi(w.getId(), "Pesan dari Ketua", pesan)) sukses++;
            }
            JOptionPane.showMessageDialog(this, "Pesan berhasil dikirim ke " + sukses + " warga.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else if (pilihan == 1) {
            // Broadcast ke warga spesifik
            WargaDAO wargaDAO = new WargaDAO();
            List<Warga> wargaList = wargaDAO.getAllWargaByLingkungan(idLingkungan);
            if (wargaList.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tidak ada warga di lingkungan ini.", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            String[] namaWarga = wargaList.stream().map(Warga::getNamaWarga).toArray(String[]::new);
            String namaDipilih = (String) JOptionPane.showInputDialog(this, "Pilih warga:", "Pilih Warga", JOptionPane.QUESTION_MESSAGE, null, namaWarga, namaWarga[0]);
            if (namaDipilih != null) {
                Warga target = wargaList.stream().filter(w -> w.getNamaWarga().equals(namaDipilih)).findFirst().orElse(null);
                if (target != null) {
                    if (NotifikasiDAO.insertNotifikasi(target.getId(), "Pesan dari Ketua", pesan)) {
                        JOptionPane.showMessageDialog(this, "Pesan berhasil dikirim ke " + namaDipilih, "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Gagal mengirim pesan.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brWarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taPesanKetua;
    // End of variables declaration//GEN-END:variables
}
