/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package usersForm.Warga;

import DataAccessObject.NotifikasiDAO;
import java.util.List;
import javax.swing.SwingUtilities;

/**
 *
 * @author HYPE AMD
 */
public class notif extends javax.swing.JPanel {

    /**
     * Creates new form notif
     */
    // Konstruktor panel, inisialisasi komponen dan load notifikasi
    public notif() {
        initComponents();
        // Ambil id warga dari parent (WargaPage)
        Integer idWarga = getIdWargaFromParent();
        if (idWarga != null) {
            loadNotifikasi(idWarga);
        } else {
            notifikasi.setText("Tidak dapat mengambil notifikasi. ID warga tidak ditemukan.");
        }
    }

    // Mengambil id warga dari parent (WargaPage)
    private Integer getIdWargaFromParent() {
        java.awt.Container parent = getParent();
        while (parent != null && !(parent instanceof WargaPage)) {
            parent = parent.getParent();
        }
        if (parent instanceof WargaPage) {
            WargaPage wp = (WargaPage) parent;
            if (wp.getWarga() != null) {
                return wp.getWarga().getId();
            }
        }
        return null;
    }

    // Mengambil dan menampilkan daftar notifikasi untuk id warga
    public void loadNotifikasi(int idWarga) {
        System.out.println("[DEBUG] loadNotifikasi dipanggil untuk idWarga=" + idWarga);
        List<String> list = NotifikasiDAO.getNotifikasiByIdWarga(idWarga);
        System.out.println("[DEBUG] Jumlah notifikasi ditemukan: " + list.size());
        StringBuilder sb = new StringBuilder();
        if (list.isEmpty()) {
            sb.append("Belum ada notifikasi untuk Anda. 😊");
        } else {
            for (String s : list) {
                String lower = s.toLowerCase();
                String emoji = "";
                if (lower.contains("penting") || lower.contains("perhatian") || lower.contains("segera")) {
                    emoji = "⚠️ ";
                } else if (lower.contains("ulang tahun") || lower.contains("selamat")) {
                    emoji = "🎉 ";
                } else if (lower.contains("broadcast") || lower.contains("semua warga") || lower.contains("ketua")) {
                    emoji = "📢 ";
                } else if (lower.contains("personal") || lower.contains("khusus") || lower.contains("anda")) {
                    emoji = "👤 ";
                } else if (lower.contains("baru") || lower.contains("pesan")) {
                    emoji = "📨 ";
                } else {
                    emoji = "🔔 ";
                }
                sb.append(emoji).append(s).append("\n\n");
            }
        }
        notifikasi.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notifikasi = new javax.swing.JTextArea();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Notifikasi");

        jLabel2.setText("Warga /");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Notifikasi");

        notifikasi.setColumns(20);
        notifikasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        notifikasi.setRows(5);
        jScrollPane2.setViewportView(notifikasi);

        btnRefresh.setBackground(new java.awt.Color(0, 204, 204));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 574, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Event handler tombol refresh notifikasi
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        handleRefresh();
    }//GEN-LAST:event_btnRefreshActionPerformed

    // Menangani aksi refresh notifikasi
    private void handleRefresh() {
        Integer idWarga = getIdWargaFromParent();
        if (idWarga != null) {
            loadNotifikasi(idWarga);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea notifikasi;
    // End of variables declaration//GEN-END:variables
}
