/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package usersForm.Warga;

/**
 *
 * @author HYPE AMD
 */
public class Penarikan extends javax.swing.JPanel {

    // Tambahan variabel untuk id warga
    private int idWarga = -1;

    // Setter untuk idWarga dan refresh data tabungan
    public void setIdWarga(int idWarga) {
        this.idWarga = idWarga;
        refreshData();
    }

    // Mengambil dan menampilkan saldo tabungan warga
    public void refreshData() {
        if (idWarga <= 0) {
            lblJumlahTabungan.setText("Rp. 0");
            return;
        }
        try {
            java.sql.Connection conn = database.Koneksi.getConnection();
            String sqlSaldo = "SELECT saldo FROM saldo_tabungan WHERE id_warga = ?";
            java.sql.PreparedStatement psSaldo = conn.prepareStatement(sqlSaldo);
            psSaldo.setInt(1, idWarga);
            java.sql.ResultSet rsSaldo = psSaldo.executeQuery();
            if (rsSaldo.next()) {
                double saldo = rsSaldo.getDouble("saldo");
                lblJumlahTabungan.setText(String.format("Rp. %,.0f", saldo));
            } else {
                lblJumlahTabungan.setText("Rp. 0");
            }
            rsSaldo.close();
            psSaldo.close();
        } catch (Exception e) {
            lblJumlahTabungan.setText("Rp. 0");
        }
    }

    // Konstruktor panel, inisialisasi komponen dan event handler tombol tarik
    public Penarikan() {
        initComponents();
        refreshData();
        btnTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarikActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblJumlahTabungan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtJumlahPenarikan = new javax.swing.JTextField();
        btnTarik = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Penarikan");

        jLabel2.setText("Warga /");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Penarikan");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tabungan Anda :");

        lblJumlahTabungan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJumlahTabungan.setText("Rp. 0");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Jumlah Penarikan :");

        txtJumlahPenarikan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnTarik.setBackground(new java.awt.Color(0, 204, 204));
        btnTarik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTarik.setText("TARIK");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Info");

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addComponent(txtJumlahPenarikan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTarik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(lblJumlahTabungan))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJumlahTabungan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJumlahPenarikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTarik)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Event handler tombol tarik tabungan
    private void btnTarikActionPerformed(java.awt.event.ActionEvent evt) {
        if (idWarga <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID Warga tidak valid! Silakan login ulang.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        String nominalStr = txtJumlahPenarikan.getText().trim().replaceAll("[^\\d.]", "");
        if (nominalStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nominal tidak boleh kosong!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        double nominal;
        try {
            nominal = Double.parseDouble(nominalStr);
            if (nominal <= 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nominal harus berupa angka lebih dari 0!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Pilihan metode penarikan
        String[] options = {"Tunai", "Transfer Rekening"};
        int choice = javax.swing.JOptionPane.showOptionDialog(
            this,
            "Pilih metode penarikan:",
            "Metode Penarikan",
            javax.swing.JOptionPane.DEFAULT_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[0]
        );
        String metode = "tunai";
        String keterangan = "Penarikan tabungan";
        if (choice == 1) { // Transfer Rekening
            javax.swing.JPanel panel = new javax.swing.JPanel();
            javax.swing.JComboBox<String> cbBank = new javax.swing.JComboBox<>(new String[]{"BCA", "BRI", "BNI", "Mandiri", "CIMB Niaga", "Bank Lain"});
            javax.swing.JTextField tfRek = new javax.swing.JTextField(15);
            panel.setLayout(new java.awt.GridLayout(2, 2, 5, 5));
            panel.add(new javax.swing.JLabel("Bank Tujuan:"));
            panel.add(cbBank);
            panel.add(new javax.swing.JLabel("No. Rekening:"));
            panel.add(tfRek);
            int result = javax.swing.JOptionPane.showConfirmDialog(this, panel, "Input Transfer Rekening", javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);
            if (result != javax.swing.JOptionPane.OK_OPTION) return;
            String bank = (String) cbBank.getSelectedItem();
            String norek = tfRek.getText();
            if (norek.trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Nomor rekening tidak boleh kosong!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            metode = "transfer";
            keterangan = "Transfer ke bank " + bank + ", No. Rek: " + norek;
        }
        // Cek saldo
        double saldo = 0;
        try {
            java.sql.Connection conn = database.Koneksi.getConnection();
            String cekSql = "SELECT saldo FROM saldo_tabungan WHERE id_warga = ?";
            java.sql.PreparedStatement cekPs = conn.prepareStatement(cekSql);
            cekPs.setInt(1, idWarga);
            java.sql.ResultSet rs = cekPs.executeQuery();
            if (rs.next()) {
                saldo = rs.getDouble("saldo");
            }
            rs.close();
            cekPs.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengambil saldo: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (saldo < nominal) {
            javax.swing.JOptionPane.showMessageDialog(this, "Saldo tabungan tidak cukup!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Proses penarikan
        try {
            java.sql.Connection conn = database.Koneksi.getConnection();
            // Insert ke tabungan
            String sql = "INSERT INTO tabungan (id_warga, jenis, jumlah, tanggal, metode, keterangan) VALUES (?, 'penarikan', ?, NOW(), ?, ?)";
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idWarga);
            ps.setDouble(2, nominal);
            ps.setString(3, metode);
            ps.setString(4, keterangan);
            int result = ps.executeUpdate();
            if (result > 0) {
                // Update saldo_tabungan
                String updateSql = "UPDATE saldo_tabungan SET saldo = saldo - ?, last_update = NOW() WHERE id_warga = ?";
                java.sql.PreparedStatement updatePs = conn.prepareStatement(updateSql);
                updatePs.setDouble(1, nominal);
                updatePs.setInt(2, idWarga);
                updatePs.executeUpdate();
                updatePs.close();
                database.Koneksi.commit();
                javax.swing.JOptionPane.showMessageDialog(this, "Penarikan tabungan berhasil!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                // Output ke text area
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                String timestamp = sdf.format(new java.util.Date());
                String outputText = String.format("[%s] Penarikan tabungan\nNominal: Rp %,.0f\nMetode: %s\nKeterangan: %s\n----------------------------------------\n", timestamp, nominal, metode, keterangan);
                output.append(outputText);
                refreshData();
            } else {
                database.Koneksi.rollback();
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal mencatat penarikan!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            ps.close();
        } catch (Exception e) {
            try { database.Koneksi.rollback(); } catch (Exception ex) {}
            javax.swing.JOptionPane.showMessageDialog(this, "Error database: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTarik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJumlahTabungan;
    private javax.swing.JTextArea output;
    private javax.swing.JTextField txtJumlahPenarikan;
    // End of variables declaration//GEN-END:variables
}
