/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package usersForm.Warga;

/**
 *
 * @author HYPE AMD
 */
public class Setoran extends javax.swing.JPanel {

    /**
     * Creates new form Setoran
     */
    public Setoran() {
        initComponents();
        bgOpsiSetor.add(rbIuran);
        bgOpsiSetor.add(rbTabungan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOpsiSetor = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtJumlahSetoran = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbTabungan = new javax.swing.JRadioButton();
        rbIuran = new javax.swing.JRadioButton();
        btnSetor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Output = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Setoran");

        jLabel2.setText("Warga /");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Setoran");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Jumlah");

        txtJumlahSetoran.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtJumlahSetoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahSetoranActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Setor untuk :");

        rbTabungan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbTabungan.setText("Tabungan Pribadi");

        rbIuran.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbIuran.setText("Iuran RT/RW");

        btnSetor.setBackground(new java.awt.Color(0, 255, 0));
        btnSetor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSetor.setText("SETOR");
        btnSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Info");

        Output.setColumns(20);
        Output.setRows(5);
        jScrollPane1.setViewportView(Output);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(txtJumlahSetoran, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSetor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(rbTabungan)
                            .addComponent(rbIuran)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJumlahSetoran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbTabungan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbIuran)
                .addGap(18, 18, 18)
                .addComponent(btnSetor)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 604, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlahSetoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahSetoranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahSetoranActionPerformed

    private void btnSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetorActionPerformed
        // Validasi input
        if (!rbTabungan.isSelected() && !rbIuran.isSelected()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih jenis setoran terlebih dahulu!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nominalStr = txtJumlahSetoran.getText().trim().replaceAll("[^\\d.]", "");
        if (nominalStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nominal tidak boleh kosong!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        double nominal;
        try {
            nominal = Double.parseDouble(nominalStr);
            if (nominal <= 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nominal harus berupa angka lebih dari 0!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Tambahkan debug print dan validasi idWarga
        System.out.println("[DEBUG] idWarga yang akan di-insert ke tabungan: " + idWarga);
        if (idWarga <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID Warga tidak valid! Silakan login ulang.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Tampilkan QRIS
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/icons/qrDana.jpg"));
        javax.swing.JLabel label = new javax.swing.JLabel(icon);
        javax.swing.JOptionPane.showMessageDialog(this, label, "Scan QRIS Dana", javax.swing.JOptionPane.PLAIN_MESSAGE);

        // Setelah QRIS ditampilkan, catat transaksi
        String jenisSetoran = rbTabungan.isSelected() ? "tabungan" : "iuran";
        String keterangan = rbTabungan.isSelected() ? "Setoran tabungan pribadi via QRIS" : "Iuran RT/RW via QRIS";

        try {
            java.sql.Connection conn = database.Koneksi.getConnection();
            
            if (rbTabungan.isSelected()) {
                // Catat ke tabel tabungan
                String sql = "INSERT INTO tabungan (id_warga, jenis, jumlah, tanggal, metode, keterangan) VALUES (?, 'setoran', ?, NOW(), 'qris', ?)";
                java.sql.PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, idWarga);
                ps.setDouble(2, nominal);
                ps.setString(3, keterangan);
                int result = ps.executeUpdate();
                
                if (result > 0) {
                    // Update saldo_tabungan
                    String cekSql = "SELECT saldo FROM saldo_tabungan WHERE id_warga = ?";
                    java.sql.PreparedStatement cekPs = conn.prepareStatement(cekSql);
                    cekPs.setInt(1, idWarga);
                    java.sql.ResultSet rs = cekPs.executeQuery();
                    
                    if (rs.next()) {
                        // Sudah ada, update saldo
                        String updateSql = "UPDATE saldo_tabungan SET saldo = saldo + ?, last_update = NOW() WHERE id_warga = ?";
                        java.sql.PreparedStatement updatePs = conn.prepareStatement(updateSql);
                        updatePs.setDouble(1, nominal);
                        updatePs.setInt(2, idWarga);
                        updatePs.executeUpdate();
                        updatePs.close();
                    } else {
                        // Belum ada, insert baru
                        String insertSql = "INSERT INTO saldo_tabungan (id_warga, saldo, last_update) VALUES (?, ?, NOW())";
                        java.sql.PreparedStatement insertPs = conn.prepareStatement(insertSql);
                        insertPs.setInt(1, idWarga);
                        insertPs.setDouble(2, nominal);
                        insertPs.executeUpdate();
                        insertPs.close();
                    }
                    rs.close();
                    cekPs.close();
                    ps.close();
                    
                    database.Koneksi.commit();
                    javax.swing.JOptionPane.showMessageDialog(this, "Setoran tabungan via QRIS berhasil dicatat!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    
                    // Output ke text area
                    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                    String timestamp = sdf.format(new java.util.Date());
                    String output = String.format("[%s] Jenis: Setoran Tabungan\nWarga: %s\nNominal: Rp %,.0f\nMetode: QRIS\nKeterangan: %s\n----------------------------------------\n",
                        timestamp, namaWarga, nominal, keterangan);
                    Output.append(output);
                    
                } else {
                    database.Koneksi.rollback();
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal mencatat setoran tabungan!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
                
            } else if (rbIuran.isSelected()) {
                // Catat ke tabel transaksi sebagai pemasukan
                String sql = "INSERT INTO transaksi (id_lingkungan, tipe, jenis, jumlah, tanggal, sumber, keterangan, id_dibuat_oleh) VALUES (?, 'pemasukan', 'Iuran Warga', ?, NOW(), ?, ?, ?)";
                java.sql.PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, idLingkungan);
                ps.setInt(2, (int) nominal);
                ps.setString(3, namaWarga);
                ps.setString(4, keterangan);
                ps.setInt(5, idWarga); // id_dibuat_oleh menggunakan id_warga
                int result = ps.executeUpdate();
                
                if (result > 0) {
                    database.Koneksi.commit();
                    javax.swing.JOptionPane.showMessageDialog(this, "Iuran RT/RW via QRIS berhasil dicatat!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    
                    // Output ke text area
                    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                    String timestamp = sdf.format(new java.util.Date());
                    String output = String.format("[%s] Jenis: Iuran RT/RW\nWarga: %s\nNominal: Rp %,.0f\nMetode: QRIS\nKeterangan: %s\n----------------------------------------\n",
                        timestamp, namaWarga, nominal, keterangan);
                    Output.append(output);
                    
                } else {
                    database.Koneksi.rollback();
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal mencatat iuran RT/RW!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
                ps.close();
            }
            
        } catch (Exception e) {
            try { database.Koneksi.rollback(); } catch (Exception ex) {}
            javax.swing.JOptionPane.showMessageDialog(this, "Error database: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSetorActionPerformed

    // Variabel untuk menyimpan data warga
    private int idWarga;
    private int idLingkungan;
    private String namaWarga;

    public void setIdWarga(int idWarga) {
        this.idWarga = idWarga;
    }

    public void setIdLingkungan(int idLingkungan) {
        this.idLingkungan = idLingkungan;
    }

    public void setNamaWarga(String namaWarga) {
        this.namaWarga = namaWarga;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Output;
    private javax.swing.ButtonGroup bgOpsiSetor;
    private javax.swing.JButton btnSetor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbIuran;
    private javax.swing.JRadioButton rbTabungan;
    private javax.swing.JTextField txtJumlahSetoran;
    // End of variables declaration//GEN-END:variables
}
